package com.yoyo.system.gui;

import com.yoyo.services.entity.Furniture;
import com.yoyo.services.manager.FurnitureManager;
import com.yoyo.system.model.FurnitureTableModel;
import java.io.IOException;
import java.util.ArrayList;

public class CreateSaleOrderPanel extends javax.swing.JPanel {

    private FurnitureManager furnitureManager;
    private ArrayList<Furniture> furnitures;
    /**
     * Creates new form CreateSaleOrderPanel
     */
    public CreateSaleOrderPanel() {
        furnitureManager = new FurnitureManager();
        // Load furnitures
        try {
            furnitureManager.loadBookings();
            furnitures = furnitureManager.getFurnitures();
        } catch (IOException ex) {
            System.err.println("Error loading furniture file");
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollPane = new javax.swing.JScrollPane();
        createOrderTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1440, 960));

        createOrderTable.setModel(new FurnitureTableModel(furnitures));
        tableScrollPane.setViewportView(createOrderTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable createOrderTable;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
