/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.yoyo.system.gui;

import com.yoyo.services.manager.PanelManager;
import com.yoyo.services.manager.SalesManager;
import com.yoyo.services.manager.UserManager;
import java.io.IOException;

/**
 *
 * @author user
 */
public class SalesPersonSalesOverviewPanel extends javax.swing.JPanel {

    private final UserManager userManager;
    
    private String furnitureSoldValue;
    private final SalesManager salesManager = new SalesManager();
    /**
     * Creates new form SalesPersonSalesOverviewPanel
     */
    public SalesPersonSalesOverviewPanel() {
        furnitureSoldValue = salesManager.totalFurnitureSold();
        userManager = new UserManager();
        try {
            userManager.loadUsers();
        } catch (IOException ex) {
            System.err.println("Error loading user file");
        }
        
        initComponents();
        initComponents();
        furnitureSoldTxt.setText(furnitureSoldValue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        furnitureSold = new javax.swing.JLabel();
        salesEarn = new javax.swing.JLabel();
        commissionEarned = new javax.swing.JLabel();
        furnitureSoldTxt = new javax.swing.JLabel();
        commissionEarnedTxt = new javax.swing.JLabel();
        salesEarnedTxt = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1440, 960));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setText("Sales Overview");

        furnitureSold.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        furnitureSold.setText("Total Furnitures Sold:");

        salesEarn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        salesEarn.setText("Total Sales Earned:");

        commissionEarned.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        commissionEarned.setText("Total Commission Earned:");

        furnitureSoldTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        furnitureSoldTxt.setText("jLabel2");

        commissionEarnedTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        commissionEarnedTxt.setText("jLabel2");

        salesEarnedTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        salesEarnedTxt.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(556, 556, 556))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(commissionEarned)
                            .addComponent(furnitureSold)
                            .addComponent(salesEarn))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(furnitureSoldTxt)
                            .addComponent(commissionEarnedTxt)
                            .addComponent(salesEarnedTxt))))
                .addContainerGap(567, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(backBtn)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(furnitureSold)
                    .addComponent(furnitureSoldTxt))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salesEarn)
                    .addComponent(salesEarnedTxt))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commissionEarned)
                    .addComponent(commissionEarnedTxt))
                .addContainerGap(440, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        PanelManager.previousPanel();
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel commissionEarned;
    private javax.swing.JLabel commissionEarnedTxt;
    private javax.swing.JLabel furnitureSold;
    private javax.swing.JLabel furnitureSoldTxt;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel salesEarn;
    private javax.swing.JLabel salesEarnedTxt;
    // End of variables declaration//GEN-END:variables
}
